// Type-safe access to the build-time image manifest.
// The manifest is generated by scripts/build-images.mjs and maps each SOURCE
// path (e.g. "/assets/images/ho-scale/1.png") to its pre-optimized derivatives.

import rawManifest from './image-manifest.json';

export interface ImageEntry {
  width: number;
  height: number;
  aspectRatio: number;
  blur: string;
  widths: number[];
  avif: Record<string, string>;
  webp: Record<string, string>;
  fallback: string;
}

const manifest = rawManifest as unknown as Record<string, ImageEntry>;

export function getImage(src: string): ImageEntry | undefined {
  return manifest[src];
}

/** Build a srcset string from a format map (width -> url). */
export function buildSrcSet(map: Record<string, string>): string {
  return Object.entries(map)
    .map(([w, url]) => `${url} ${w}w`)
    .join(', ');
}

/** Data for a responsive <link rel="preload" as="image"> of the AVIF variants. */
export function preloadLinkProps(src: string, sizes: string) {
  const entry = manifest[src];
  if (!entry) return null;
  return {
    imageSrcSet: buildSrcSet(entry.avif),
    imageSizes: sizes,
    href: entry.fallback, // required href; browser uses srcset when supported
  };
}

/** Largest available variant at or below a target width (for preloading a sensible size). */
export function pickWidth(entry: ImageEntry, target: number): string {
  const widths = entry.widths;
  const chosen = widths.find((w) => w >= target) ?? widths[widths.length - 1];
  return entry.avif[String(chosen)] ?? entry.webp[String(chosen)] ?? entry.fallback;
}

export type { ImageEntry as Manifest };
